# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
- group: StaticSiteSecrets

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
     versionSpec: '18.x'
  displayName: 'Install Node.js'
  
- script: npm install -g @azure/static-web-apps-cli
  displayName: 'install SWA CLI'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '.'
    output_location: ''
    azure_static_web_apps_api_token: '$(deployment_token)'
  displayName: 'Deploy to Azure Static Web App'

